### ISSUE TITLE
Output path on MacOS

### ISSUE THREAD

**Issue by borkdude** [RaidAndFade/javadoc-json-doclet#1]
Thank you for this fine tool.

A minor issue, but on MacOS it creates a weird folder so the path to a JSON file looks like this:

```
.\\docs\\java.lang.Thread.json
```

You probably want to use the System property `file.separator` there:

https://github.com/RaidAndFade/javadoc-json-doclet/blob/master/src/com/raidandfade/JsonDoclet/Main.java#L18

and there:

https://github.com/RaidAndFade/javadoc-json-doclet/blob/master/src/com/raidandfade/JsonDoclet/Main.java#L75

**Comment by RaidAndFade** [comment]
You're right. I'll fix this when i get the chance.
