### ISSUE TITLE
json to MD mkdocs

### ISSUE THREAD

**Issue by Llumbroso** [RaidAndFade/javadoc-json-doclet#2]
How do you produce the md file for mkdocs from the json generate ? 

Thank you.

**Comment by RaidAndFade** [comment]
this addon specifically makes json files instead of the regular html files. If you want to make md files you should either look elsewhere or make your own converter from json to md.

**Comment by Llumbroso** [comment]
Hi !
To create your https://github.com/RaidAndFade/gct-api-docs/blob/master/docs/javadoc.md, do you have a tools ? 

Thank you

**Comment by RaidAndFade** [comment]
No that was made manuallyOn Sep. 17, 2019 4:12 a.m., Llumbroso <notifications@github.com> wrote:Hi !
To create your https://github.com/RaidAndFade/gct-api-docs/blob/master/docs/javadoc.md, do you have a tools ?
Thank you
